name: Go

on:
  push:
    branches:
  pull_request:
    branches:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: cd main && go get && go build -v

    - name: Test
      run: cd main && go get && go test -v
